language: php

php:
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION="3.0.*"
    - php: 7.2
      env: SYMFONY_VERSION="3.0.*"
    - php: 7.1
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.3
      env: SYMFONY_VERSION="4.4.*"
    - php: 7.3
      env: SYMFONY_VERSION="5.0.*"
    - php: 7.4
      env: SYMFONY_VERSION="5.0.*"
    - php: 7.4
      env: SYMFONY_VERSION="5.1.*"
    # bleeding edge (unreleased dev versions where failures are allowed):
    - php: nightly # PHP 8
      env: SYMFONY_VERSION="5.2.*"
  allow_failures:
    - env: SYMFONY_VERSION="5.2.*"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then COMPOSER_MEMORY_LIMIT=-1 composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - |
    # Set composer's platform to php 7.4 if we're on php 8
    echo $TRAVIS_PHP_VERSION
    if [[ $TRAVIS_PHP_VERSION = 'nightly' ]]; then
      echo "Set composer's platform to php 7.4"
      composer config platform.php 7.4.99
    fi
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --coverage-text
