language: php

php:
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_VERSION="3.0.*@dev"
    - php: 7.1
      env: SYMFONY_VERSION="3.0.*@dev"
    - php: 7.2
      env: SYMFONY_VERSION="3.0.*@dev"
    - php: 7.1
      env: SYMFONY_VERSION="4.0.*@dev"
    - php: 7.2
      env: SYMFONY_VERSION="4.0.*@dev"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --coverage-text
